[plugins]

[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
