return {
  "nvim-treesitter/nvim-treesitter",
  lazy = true,
  opts = {
    ensure_installed = {
      "bash",
      "elm",
      "gleam",
      "go",
      "hcl",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "terraform",
      "vim",
      "yaml",
    },
  },
}
