theme = "dracula_nk"

[editor]
auto-pairs = true
true-color = true

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
y = ":clipboard-yank-join"
Y = ":clipboard-yank"
R = ":clipboard-paste-replace"
c = [":clipboard-yank-join", "delete_selection"]

[keys.select]
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
y = ":clipboard-yank-join"
Y = ":clipboard-yank"
R = ":clipboard-paste-replace"
c = [":clipboard-yank-join", "delete_selection"]
