[[language]]
name = "go"
auto-format = true
formatter = { command = "gofumpt" }

[language-server.gopls]
command = "gopls"
# config.gofumpt = true
# config.goimports = true
# config.ui.diagnostic.staticcheck = true

[[language]]
name = "templ"
auto-format = true
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "--quiet", "-"]}

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
language-id = "javascript"
scope = "source.js"
injection-regex = "^(js|javascript)$"
file-types = ["js", "mjs"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
[language.auto-pairs]
# none

[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml"]
